modLoader="kotlinforforge"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/denis0001-dev/MCDigitalEcosystem/issues"

[[mods]]
modId="mcdigitalecosystem"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"

[[dependencies.mcdigitalecosystem]]
modId="forge"
mandatory=true
versionRange="[47.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mcdigitalecosystem]]
modId="kotlinforforge"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"

